### ISSUE TITLE
"ME Item Interface" right click interface not working on "Applied Energistics 2" mod with Ledger

### ISSUE THREAD

**Issue by cloudykira** [QuiltServerTools/Ledger#117] opened 2021-11-17 23:03 UTC
### Expected behavior

[Without Ledger working as intended - interface opening on right click](https://user-images.githubusercontent.com/91432991/142295767-75ca4687-7de1-4282-81b0-6720b4264683.png)

### Observed/actual behavior

[With Ledger not working - nothing happens on right click and errors in server log](https://user-images.githubusercontent.com/91432991/142295827-c5fdd42a-c839-42a4-aff9-c0fae0a76089.png)

### Steps/models to reproduce

installed mods:

```
appliedenergistics2-9.0.0-beta.2.jar
fabric-api-0.42.1+1.17.jar
fabric-language-kotlin-1.6.5+kotlin.1.5.31.jar
ledger-1.1.1.jar
```

go to creative
place item "ME Item Interface" to world
right click to it
must be interface if everything working

### What operating system are you running

Linux

### Minecraft version

1.17.1

### Ledger version

1.1.1

### Logs

https://pastebin.com/raw/JcNRqLsy

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

similar issue reported to mod: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5552
they said report it to ledger

**Comment by PotatoPresident** [comment] 2021-11-18 03:27
Duplicate of #107 
Update to [latest actions build](https://github.com/QuiltServerTools/Ledger/actions?query=branch%3Amaster)

**Closed by PotatoPresident** 2021-11-18 03:27 UTC
Labels: bug
