### ISSUE TITLE
Ledger incompatible with FabricProxy-Lite

### ISSUE THREAD

**Issue by Gobidev** [QuiltServerTools/Ledger#118] opened 2021-11-19 13:47 UTC
### Expected behavior

Server should start with both mods installed.

### Observed/actual behavior

Server crashes when both mods are installed simultaniously, no issue with them seperatly installed.

Server log:
```
[14:36:14] [main/INFO]: Loading for game Minecraft 1.17.1
[14:36:14] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[14:36:14] [main/INFO]: Loading 53 mods:
	- autoconfig1u 3.3.1
	- fabric 0.42.1+1.17
	- fabric-api-base 0.4.0+5847535018
	- fabric-api-lookup-api-v1 1.3.1+5847535018
	- fabric-biome-api-v1 3.2.2+5847535018
	- fabric-command-api-v1 1.1.4+5847535018
	- fabric-commands-v0 0.2.3+5847535018
	- fabric-containers-v0 0.1.13+5847535018
	- fabric-content-registries-v0 0.3.1+5847535018
	- fabric-crash-report-info-v1 0.1.6+5847535018
	- fabric-dimensions-v1 2.0.13+5847535018
	- fabric-entity-events-v1 1.3.1+5847535018
	- fabric-events-interaction-v0 0.4.11+5847535018
	- fabric-events-lifecycle-v0 0.2.2+5847535018
	- fabric-game-rule-api-v1 1.0.8+5847535018
	- fabric-item-api-v1 1.2.5+5847535018
	- fabric-item-groups-v0 0.3.1+5847535018
	- fabric-language-kotlin 1.6.5+kotlin.1.5.31
	- fabric-lifecycle-events-v1 1.4.5+5847535018
	- fabric-loot-tables-v1 1.0.5+5847535018
	- fabric-mining-level-api-v1 1.0.2+6d0fac4218
	- fabric-mining-levels-v0 0.1.5+6d0fac4218
	- fabric-networking-api-v1 1.0.14+5847535018
	- fabric-networking-blockentity-v0 0.2.12+5847535018
	- fabric-networking-v0 0.3.3+5847535018
	- fabric-object-builder-api-v1 1.10.11+6d0fac4218
	- fabric-object-builders-v0 0.7.5+6d0fac4218
	- fabric-particles-v1 0.2.5+5847535018
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fabric-registry-sync-v0 0.7.13+5847535018
	- fabric-rendering-data-attachment-v1 0.1.6+5847535018
	- fabric-rendering-fluids-v1 0.2.1+6d0fac4218
	- fabric-resource-loader-v0 0.4.9+5847535018
	- fabric-screen-handler-api-v1 1.1.9+5847535018
	- fabric-structure-api-v1 1.1.14+5847535018
	- fabric-tag-extensions-v0 1.2.2+5847535018
	- fabric-tool-attribute-api-v1 1.3.1+eb76084f18
	- fabric-transfer-api-v1 1.5.1+6d0fac4218
	- fabricloader 0.12.5
	- fabricproxy-lite 1.1.5
	- java 17
	- ledger 1.1.1
	- minecraft 1.17.1
	- org_jetbrains_kotlin_kotlin-reflect 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.5.31
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.0
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.0
	- packet_tweaker 0.2.0-1.17-pre1
	- server_translations_api 1.4.5+1.17
[14:36:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/adrian/Minecraft/Fabric/1.17.1/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[14:36:14] [main/INFO]: Compatibility level set to JAVA_16
[14:36:15] [main/ERROR]: Mixin prepare for mod server_translations_api failed preparing text.BaseTextMixin in server_translations_api.mixin.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: server_translations_api.mixin.json:text.BaseTextMixin target net.minecraft.class_2554 was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: server_translations_api.mixin.json:text.BaseTextMixin target net.minecraft.class_2554 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:566) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [fabric-server-launch.jar:?]


```

### Steps/models to reproduce

1. Install fabricmc server on latest version (fabricloader 0.12.5, Minecraft 1.17.1)
2. Install latest ledger version (1.1.1) along with fabric-api (0.42.1) and fabric-language-kotlin (1.6.5)
3. Install FabricProxy-Lite (1.1.5) [(here)](https://github.com/OKTW-Network/FabricProxy-Lite/releases)
4. Start the server
5. Server will crash

### What operating system are you running

Linux

### Minecraft version

1.17.1

### Ledger version

1.1.1

### Logs

https://www.toptal.com/developers/hastebin/iqiyiyonat.yaml

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Patbox** [comment] 2021-11-19 13:53
If possible, downgrade your fabric api version to 0.41.3

**Comment by Gobidev** [comment] 2021-11-19 13:57
That worked, thanks!
I will leave the issue open though, since that fabric-api version will probably not be available for 1.18.

**Comment by Tom-The-Geek** [comment] 2021-11-19 14:50
This appears to be caused by FabricProxy-Lite rather than Ledger, and has been reported to them at OKTW-Network/FabricProxy-Lite#13. We'll keep this open to avoid duplicates though

**Comment by yitzy299** [comment] 2021-11-28 10:11
The issue on fabricproxy-lite has been fixed, closing here

**Closed by yitzy299** 2021-11-28 10:11 UTC
Labels: bug, external issue, mod compat
